
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class AboutUs extends ContentItem {
    public contactEmail3: Elements.TextElement;
    public contactEmail1: Elements.TextElement;
    public mobileNumber2: Elements.NumberElement;
    public facebookUrl: Elements.TextElement;
    public mobileNumber3: Elements.NumberElement;
    public contactEmail2: Elements.TextElement;
    public mobileNumber1: Elements.NumberElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'contact_email_3') {
                    return 'contactEmail3';
                }
                if (elementName === 'contact_email_1') {
                    return 'contactEmail1';
                }
                if (elementName === 'mobile_number_2') {
                    return 'mobileNumber2';
                }
                if (elementName === 'facebook_url') {
                    return 'facebookUrl';
                }
                if (elementName === 'mobile_number_3') {
                    return 'mobileNumber3';
                }
                if (elementName === 'contact_email_2') {
                    return 'contactEmail2';
                }
                if (elementName === 'mobile_number_1') {
                    return 'mobileNumber1';
                }
                return elementName;
            })
        });
    }
}
