
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class AboutUs extends ContentItem {
    public facebookUrl: Elements.TextElement;
    public bannerSlogan: Elements.TextElement;
    public contactNumber2: Elements.TextElement;
    public contactNumber1: Elements.NumberElement;
    public bannerImage: Elements.AssetsElement;
    public contactEmail1: Elements.TextElement;
    public pageName: Elements.TextElement;
    public contactEmail3: Elements.TextElement;
    public contactEmail2: Elements.TextElement;
    public whatWeDo: Elements.RichTextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'facebook_url') {
                    return 'facebookUrl';
                }
                if (elementName === 'banner_slogan') {
                    return 'bannerSlogan';
                }
                if (elementName === 'contact_number_2') {
                    return 'contactNumber2';
                }
                if (elementName === 'contact_number_1') {
                    return 'contactNumber1';
                }
                if (elementName === 'banner_image') {
                    return 'bannerImage';
                }
                if (elementName === 'contact_email_1') {
                    return 'contactEmail1';
                }
                if (elementName === 'page_name') {
                    return 'pageName';
                }
                if (elementName === 'contact_email_3') {
                    return 'contactEmail3';
                }
                if (elementName === 'contact_email_2') {
                    return 'contactEmail2';
                }
                if (elementName === 'what_we_do') {
                    return 'whatWeDo';
                }
                return elementName;
            })
        });
    }
}
